title: Slavin-Ross Archive ğŸ“šğŸ—„ï¸

theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib
  - include
  - bin
  - etc
  - share

include:
  - _pages

header_pages:
  - michael.html
  - barbara.html

minima:
  header_pages:
    - michael.html
    - barbara.html